apiVersion: scaffolder.backstage.io/v1beta3
kind: Component
metadata:
  name: ${{values.name | dump}}
  description: ${{values.description | dump}}
spec:
  lifecycle: experimental
  owner: ${{values.owner | dump}}
  type: documentation
